Update Microsoft.ApplicationInsights.AspNetCore NuGet package to the latest stable version
MicrosoftDocs/mslearn-microservices-architecture pull request #12
Opened 2022-03-04 02:58 UTC by Tianyun-G

1.Upgrade the projects from .NET Core 2.x to .NET 6 and update Microsoft.ApplicationInsights.AspNetCore NuGet package to the latest stable version.

2.Update files:

i. src/after/DroneDelivery-after/Controllers/HomeController.cs
ii. src/after/DroneDelivery-after/DroneDelivery-after.csproj
iii. src/after/DroneDelivery-after/Program.cs
iv. src/after/DroneDelivery-after/Services/PackageServiceCaller.cs
v. src/after/DroneDelivery-after/Startup.cs
vi. src/after/DroneDelivery.Common/DroneDelivery.Common.csproj
vii. src/after/PackageService/PackageService.csproj
viii. src/before/DroneDelivery-before/Controllers/HomeController.cs
ix. src/before/DroneDelivery-before/DroneDelivery-before.csproj
x. src/before/DroneDelivery-before/Program.cs
xi. src/before/DroneDelivery-before/Startup.cs
xii. src/before/DroneDelivery.Common/DroneDelivery.Common.csproj

2022-03-07 18:54 UTC, scottaddie requested changes

2022-03-07 18:54 UTC, scottaddie commented on src/after/DroneDelivery-after/DroneDelivery-after.csproj
>      <PackageReference Include="Microsoft.AspNetCore.App" />
This metapackage should be removed when using .NET 6.0.
```suggestion
```

2022-03-07 18:54 UTC, scottaddie commented on src/after/DroneDelivery-after/Services/PackageServiceCaller.cs
> +            StringContent httpContent = new StringContent(jsonString, System.Text.Encoding.UTF8, "application/json");
Prefer `var` in instantiation cases like this where the type is obvious.

```suggestion
            var httpContent = new StringContent(jsonString, System.Text.Encoding.UTF8, "application/json");
```

2022-03-07 18:54 UTC, scottaddie commented on src/after/DroneDelivery-after/Controllers/HomeController.cs
> +                StringContent httpContent = new StringContent(jsonString, System.Text.Encoding.UTF8, "application/json");
```suggestion
                var httpContent = new StringContent(jsonString, System.Text.Encoding.UTF8, "application/json");
```

2022-03-07 18:54 UTC, scottaddie commented on src/before/DroneDelivery-before/Controllers/HomeController.cs
> +                StringContent httpContent = new StringContent(jsonString, System.Text.Encoding.UTF8, "application/json");
```suggestion
                var httpContent = new StringContent(jsonString, System.Text.Encoding.UTF8, "application/json");
```

2022-03-07 18:54 UTC, scottaddie commented on src/before/DroneDelivery-before/DroneDelivery-before.csproj
>      <PackageReference Include="Microsoft.AspNetCore.App" />
```suggestion
```

2022-03-15 07:01 UTC, v-xuto commented
@scottaddie - We have updated, please rereview this PR. Thanks a lot.

2022-03-24 01:52 UTC, scottaddie approved these changes

2022-03-24 07:15 UTC, v-xuto commented
#sign-off

2022-04-01 07:14 UTC, v-xuto commented
#sign-off

2022-04-01 07:23 UTC, v-xuto commented
@scottaddie  Please help merge this PR. I have added `#sign-off`, but there's no reaction here.

2022-04-07 03:21 UTC, v-xuto commented
#sign-off

2022-04-14 22:22 UTC, markjulmar approved these changes

2022-04-14 22:22 UTC, merged